# Generated by Django 5.0.6 on 2024-06-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='accountNo',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='accountType',
            field=models.CharField(choices=[('Savings', 'Savings'), ('current', 'current')], max_length=10),
        ),
    ]
