# Generated by Django 5.0.6 on 2024-06-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_userbankaccount_accountno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='isBankRupt',
            field=models.BooleanField(default=False),
        ),
    ]
