# Generated by Django 5.0.6 on 2024-05-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='car',
            new_name='carr',
        ),
    ]
