# Generated by Django 5.0.6 on 2024-05-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_rename_car_comment_carr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='carr',
            new_name='cars',
        ),
    ]
