# Generated by Django 5.0.4 on 2024-06-02 16:05

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.user_directory_path),
        ),
    ]
