# Generated by Django 5.0.4 on 2024-05-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumName', models.CharField(max_length=30)),
                ('albumRelaseData', models.DateTimeField(auto_now_add=True)),
                ('RatingNow', models.CharField(choices=[('one', '1'), ('two', '2'), ('3', '3'), ('4', '4')], max_length=20)),
                ('Musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musician')),
            ],
        ),
    ]
