# Generated by Django 5.0.4 on 2024-05-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('big_integerFeild', models.BigIntegerField()),
                ('binaryFeild', models.BinaryField()),
                ('booleanFeild', models.BooleanField()),
                ('charFeild', models.CharField(max_length=30)),
                ('dateFeild', models.DateField()),
                ('dateTimeFeild', models.DateTimeField()),
                ('decimalFeild', models.DecimalField(decimal_places=5, max_digits=5)),
                ('emailFeild', models.EmailField(max_length=254)),
            ],
        ),
    ]
