# Generated by Django 5.0.6 on 2024-06-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_isbankrupt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='isBankRupt',
        ),
    ]
