# Generated by Django 5.0.4 on 2024-04-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTapp', '0002_student_father_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
    ]
