# Generated by Django 5.0.4 on 2024-05-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='id',
        ),
        migrations.AddField(
            model_name='musician',
            name='Mid',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
    ]
